image: gitlab.list-group.com:5000/isp-bu/libs/docker-img-maven-node:java8-node10-chrome

cache:
  key: isp-bu-groot-cache
  paths:
  - node_modules/

stages:
- test
- package
- deploy

before_script:
- npm install

test-angular:
  stage: test
  script:
  - ./node_modules/.bin/ng test --watch=false --code-coverage=true --browsers=ChromeHeadlessNoSandbox
  artifacts:
    paths:
      - coverage/

built-angular-aot:
  stage: package
  script:
      - npm run package

#pages:
#  stage: deploy
#  dependencies:
#    - test-angular
#  script:
#    - mv coverage/ public/
#  artifacts:
#    paths:
#      - public
#    expire_in: 30 days
#  only:
#    - master

deploy-demo-doc:
  stage: deploy
  dependencies:
    - test-angular
  script:
    - npm run deploy-demo-doc
  only:
    - master
