stages:
  - angular
  - docker
  - openshift

variables:
  NPM_CONFIG_REGISTRY: "https://artifactory.list-group.com/artifactory/api/npm/npm/"
  DOCKER_IMAGE_NAME: "artifactory.list-group.com/isp/groot"
  OPENSHIFT_PROJECT: "isp-groot"
  OPENSHIFT_APP: "groot"

test-angular:
  image: artifactory.list-group.com/isp/libs/docker-img-maven-node/java8-node10-chrome
  stage: angular
  script:
  - http_proxy="http://192.168.199.33:8080"
  - https_proxy="http://192.168.199.33:8080"
  - no_proxy="localhost, 127.0.0.1, 127.0.0.0/8, ::1, .list-group.com, list.it, 192.168.198.0/24, 192.168.200.0/24, 10.91.193.0/24, 10.91.194.0/24, 10.91.195.0/24, 10.91.197.0/24, 10.91.198.0/24, 10.91.201.0/24, 192.168.1.0/24, 192.168.101.0/24, 192.168.12.0/24, 192.168.15.0/24, 192.168.191.0/24, 192.168.195.0/24, 192.168.197.0/24, 192.168.198.0/24, 192.168.199.0/24, 192.168.2.0/24, 192.168.20.0/24, 192.168.22.0/24, 192.168.232.0/24, 192.168.200.0/24, 192.168.202.0/24, 192.168.203.0/24, 192.168.204.0/24, 192.168.210.0/24, 192.168.3.0/24, 192.168.70.0/24, 192.168.71.0/24, 192.168.73.0/24, 192.168.77.0/24"
  - npm cache --force clean
  - npm ci
  - ./node_modules/.bin/ng test --watch=false --code-coverage=true --browsers=ChromeHeadlessNoSandbox
  - npm run package
  - npm run build-demo-app
  artifacts:
    paths:
      - dist/groot-tester
  cache:
    key: isp-bu-groot-cache
    paths:
      - node_modules/

build-docker-image:
  image: docker:18
  stage: docker
  script:
    - echo $ARTIFACTORY_DEPLOY_PASSWORD | docker login -u $ARTIFACTORY_DEPLOY_USERNAME --password-stdin  artifactory.list-group.com
    - docker build --pull --build-arg http_proxy=$http_proxy --build-arg https_proxy=$https_proxy -t $DOCKER_IMAGE_NAME:${CI_COMMIT_TAG:-latest} .
    - docker push $DOCKER_IMAGE_NAME:${CI_COMMIT_TAG:-latest}
  only:
    - master

deploy-on-openshift:
  image: openshift/origin-cli
  stage: openshift
  script:
    - oc login $OPENSHIFT_URL -u $OPENSHIFT_LOGIN -p $OPENSHIFT_PASSWORD --insecure-skip-tls-verify
    - oc project $OPENSHIFT_PROJECT
    - oc import-image $OPENSHIFT_PROJECT/$OPENSHIFT_APP --from=$DOCKER_IMAGE_NAME
  only:
    - master
  allow_failure: true
